### ISSUE TITLE
Getting error while minting token

### ISSUE THREAD

**Issue by ranjancse26** [TimmyIsANerd/rariblenftminter#1]
Please help me in resolving the attached issue while minting the token. 

let res = await Moralis.Plugins.rarible.lazyMint

![image](https://user-images.githubusercontent.com/2565797/161382877-f31d43ee-6db4-466b-8750-0130c58a44a9.png)

**Comment by TimmyIsANerd** [comment]
![image](https://user-images.githubusercontent.com/33554538/161426327-be8d07de-29be-4599-be30-374d5b7a0215.png)

You need to make sure to install the Rarible Plugin on your Moralis Server
